apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-mariadb
  namespace: db
data:
  master.cnf: | 
    [mariadb]
    log-bin
    log-basename=my-mariadb
  slave.cnf: | 
    [mariadb]
    log-bin
    log-basename=my-mariadb
  master.sql: |
    CREATE USER 'radin'@'%' IDENTIFIED BY '123';
    GRANT REPLICATION REPLICA ON *.* TO 'radin'@'%';
    CREATE DATABASE primary_db;
  slave.sql: |
    CHANGE MASTER TO
      MASTER_HOST='mariadb-0.db-svc.db.svc.cluster.local',
      MASTER_USER='radin',
      MASTER_PASSWORD='123',
      MASTER_CONNECT_RETRY=10;




